export const CustomerActionTypes = {
    FETCH_CUSTOMERS_START: "FETCH_CUSTOMERS_START",
    FETCH_CUSTOMERS_SUCCESS: "FETCH_CUSTOMERS_SUCCESS",
    FETCH_CUSTOMERS_FAILURE: "FETCH_CUSTOMERS_FAILURE",
    ADD_CUSTOMER_START: "ADD_CUSTOMER_START",
    ADD_CUSTOMER_SUCCESS: "ADD_CUSTOMER_SUCCESS",
    ADD_CUSTOMER_FAILURE: "ADD_CUSTOMER_FAILURE",
    UPDATE_CUSTOMER_START: "UPDATE_CUSTOMER_START",
    UPDATE_CUSTOMER_SUCCESS: "UPDATE_CUSTOMER_SUCCESS",
    UPDATE_CUSTOMER_FAILURE: "UPDATE_CUSTOMER_FAILURE",
    DELETE_CUSTOMER_START: "DELETE_CUSTOMER_START",
    DELETE_CUSTOMER_SUCCESS: "DELETE_CUSTOMER_SUCCESS",
    DELETE_CUSTOMER_FAILURE: "DELETE_CUSTOMER_FAILURE"
}